#if !canImport(ObjectiveC)
import XCTest

extension MotionDatasetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MotionDatasetTests = [
        ("testExample", testExample),
        ("testExample2", testExample2),
        ("testExample3", testExample3),
        ("testExample4", testExample4),
        ("testExample5", testExample5),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(MotionDatasetTests.__allTests__MotionDatasetTests),
    ]
}
#endif
