#if !canImport(ObjectiveC)
import XCTest

extension MotionDatasetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MotionDatasetTests = [
       ("testSerializeMotionSample", testSerializeMotionSample),
       ("testSerializeMotionDataJSON", testSerializeMotionDataJSON),
       ("testSerializeMotionDataBinary", testSerializeMotionDataBinary),
       ("testReadBinaryMotionData", testReadBinaryMotionData),
    ]
}
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(MotionDatasetTests.__allTests__MotionDatasetTests),
    ]
}
#endif
