#if !canImport(ObjectiveC)
import XCTest

extension MotionDatasetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MotionDatasetTests = [
       ("testSerializeMotionSample", testSerializeMotionSample),
       ("testSerializeMotionDataJSON", testSerializeMotionDataJSON),
       ("testSerializeMotionDataBinary", testSerializeMotionDataBinary),
       ("testReadBinaryMotionData", testReadBinaryMotionData),
    ]
}

extension LangMotionTransformerTests {
    static let __allTests__LangMotionTransformerTests = [
        // ("testTimeDistributedMixtureModel", testTimeDistributedMixtureModel),        
        ("testForwardPass", testForwardPass),
        // ("testX10Performance", testX10Performance),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        // testCase(MotionDatasetTests.__allTests__MotionDatasetTests),
        testCase(LangMotionTransformerTests.__allTests__LangMotionTransformerTests)
    ]
}
#endif
